name: Linting Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Lint HTML
        run: npx htmlhint src/**/*.html

      - name: Lint CSS
        run: npx stylelint styles/**/*.css
